### ISSUE TITLE
standard cursor appears in Safari 

### ISSUE THREAD

**Issue by darbre** [hongkiulam/ipad-cursor-js#1]
Hi! 
I set the `data-cursor` attribute to element `a` and when I click in Safari, a standard cursor appears. When you start moving the mouse, the standard cursor disappears.

Perhaps you can help me solve this problem?

Thanks in advance

**Comment by hongkiulam** [comment]
Hey! Thanks for raising this :)

I've had a quick test and managed to reproduce. I found that clicking a link which navigates to another page causes the standard cursor to appear, and then on the new page the custom cursor appears to snap back into place from the top left corner.

There's not a lot I can do to prevent the standard cursor showing up, but I can fix the weird position jumping of the cursor
